
/*
    these are tooltips in format:
    "<original abbreviation>:<description-english> - <description-polish>"
    one per line - alphabetical order
    "XXXYYYZZZ" must be the last one
    
    marked with XXX - probably present in the dictionary, but not on its cheatsheet
 */

    static QString tab[] = {
		"Accts:accountancy - ksiêgowo¶æ",
		"adj:adjective - przymiotnik",
		"adj phr:adjectival phrase - fraza przymiotnikowa",
		"Admin:administration - administracja",
		"adv:adverb - przys³ówek",
		"adv phr:adverbial phrase",
		"Advertg:advertising - reklama",
		"Aerosp:aerospace - kosmonautyka",
		"Agric:agriculture - rolnictwo",
		"also:also - tak¿e",
		"Anat:anatomy - anatomia",
		"Anthrop:anthropology - antropologia",
		"Antiq:antiquity - staro¿ytno¶æ",
		"arch:archaic - archaiczne",
		"Archeol:archeology - archeologia",
		"Archit:architecture - architektura",
		"Art:art - sztuka",
		"Astrol:astrology - astrologia",
		"Astron:astronomy - astronomia",
		"Audio:audio - audiotechnika",
		"Austral:Australian - australijskie",
		"Aut:automobile - motoryzacja",
		"aux:auxiliary - posi³kowy",
		"Aviat:aviation - lotnictwo",
		"baby talk:baby talk - mowa dzieci",
		"before vowel:before vowel - przed samog³osk±",	/// XXX
		"Bible:bible - Biblia",
		"Biol:biology - biologia",
		"Bot:botany - botanika",
		"Can:Canadian - kanadyjskie",
		"Chem:chemistry - chemia",
		"Cin:cinema - kinematografia",
		"Civ Eng:civil engineering - in¿ynieria l±dowa",
		"Comm:commerce - handel",
		"comp:comparative - stopieñ wy¿szy",
		"Comput:computng - informatyka i komputery",
		"conj:conjunction - spójnik",
		"conj phr:conjunction phrase - spójnik z³o¿ony",
		"Constr:construction - budownictwo",
		"contracted:contracted - wersja skrócona",	/// XXX
		"controv:controversial - kontrowersyjne",
		"Cosmet:cosmetics - kosmetyka",
		"Culin:culinary - kulinaria",
		"Dance:dance - taniec",
		"Dent:dentistry - stomatologia",
		"dat:dated - przestarza³e",
		"det:determiner - okre¶lnik",
		"def art.:definiet article - przedimek okre¶lony",
		"dial:dialect - dialektalne",
		"Ecol:ecology - ekologia",
		"Econ:economy - ekonomia",
		"Educ:education - edukacja",		/// XXX
		"Elec:electricity - elektryka",
		"Electron:electronics - elektronika",
		"Equest:equestrianizm - je¼dziectwo",
		"euph:euphemistic - eufemizm",
		"excl:exclamation - wykrzynik",
		"f:feminine - ¿eñski",
		"Fashn:fashion - moda",
		"fig:figurative - przeno¶ne",
		"Fin:finance - finanse",
		"Fishg:fishing - rybo³ówstwo",
		"fml:formal - oficjalne, ksi±¿kowe",
		"Games:games - gry i zabawy",
		"GB:British English - angielszczyzna brytyjska",
		"Geog:geography - geografia",
		"Geol:geology - geologia",
		"Herald:heraldry - heraldyka",
		"Hist:history - historia",
		"Hort:horticulture - ogrodnictwo",
		"hum:humorous - ¿artobliwe",
		"Hunt:hunting - my¶listwo",
		"Ind:industry - przemys³",
		"Insur:insurance - ubezpieczenia",
		"indef art.:indefinite article - przedimek nieokre¶lony",
		"infml:informal - potoczne, nieoficjalne",
		"Insur:insurance - ubezpieczenia",
		"inv:invariable - niezmienny",		/// XXX
		"Ir:Irish - irlandzkie",
		"iron:ironic - ironiczne",
		"journ:journalese - dziennikarskie",
		"Journ:journalism - dziennikarstwo",
		"Jur:law - prawo",
		"Ling:linguistics - jêzykoznawstwo",
		"linking verb:linking verb - spójka",
		"liter:literary - literackie",
		"Literat:literature - literatura",
		"m/f:masculine/feminine - mêski/¿eñski",
		"m:masculine - mêski",
		"Math:mathematics - matematyka",
		"Mech:mechanics - mechanika",
		"Med:medicine - medycyna",
		"Meas:measure - jednostki miary",
		"Meteorol:meteorology - meteorologia",
		"Mgmt:management - zarz±dzanie",
		"Mil:military - wojskowo¶æ",
		"Mil Naut:navy - marynarka wojenna",
		"Miner:mineralogy - mineralogia",		
		"Mining:mining - górnictwo",		/// XXX
		"modal aux:modal auxiliary verb - czasownik posi³kowo-modalny",
		"modif:modifier - przydawka rzeczowna",
		"Mus:music - muzyka",
		"Mythol:mythology - mitologia",
		"n:noun - rzeczownik",
//		"n:neuter - nijaki",
		"Naut:nautical - ¿eglarstwo",
		"neg:negation - negacja",		/// XXX
		"npl:noun plural - rzeczownik w liczbie mnogiej",
		"Nucl:nuclear physics - fizyka j±drowa",
		"offensive:offensive - obra¼liwe",
		"onomat:onomatopoeia - onomatopeja",
		"or:or - lub",
		"pej:pejorative - pejoratywne",
		"pers.:person - osoba",
		"Pharm:pharmacology - farmakologia",
		"Philos:philosophy - filozofia",
		"Phon:phonetics - fonetyka",		/// XXX ale jest, np. transcription
		"Phot:photography - fotografia",
		"Phys:physics - fizyka",
		"Physiol:physiology - fizjologia",
		"pl:plural - liczba mnoga",
		"plt:plurale tantum - rzeczownik wystêpuj±cy tylko w liczbie mnogiej",
		"Pol:politics - polityka",
		"Post:poczta - postal services",
		"pp:past participle - imies³ów przesz³y",
		"pp adj:past participle adjective - imies³ów przymiotnikowy bierny",
		"prep:preposition - przyimek",
		"prep phr:prepositional phrase - przymiek z³o¿ony",
		"pres:present tense - czas tera¼niejszy",
		"prn:proper noun - nazwa w³asna",
		"Print:printing - drukarstwo",
		"pron:pronoun - zaimek",
		"Prov:proverb - przys³owie",
		"prp:present participle - imies³ów czasu tera¼niejszego",
		"prp adj:present participle adjective - imies³ów przymiotnikowy czynny",
		"Psych:psychology - psychologia",
		"pt:past tense - czas przesz³y",
		"Publg:publishing - edytorstwo",
		"quantif:quantifier - kwantyfikator",
		"ra:rare - rzadkie",
		"Radio:radio - radio",
		"Rail:railway - kolejnictwo",
		"Relig:religion - religia",
		"Sch:school - szkolnictwo",
		"Sci:sciences - nauki ¶cis³e",
		"Scot:Scottish - szkockie",
		"Sewing:sewing - krawiectwo",
		"sg:singular - liczba pojedyncza",
		"sl:slang - slangowe",
		"Sociol:sociology - socjologia",
		"spec:specialist - specjalistyczne",
		"Sport:sport - sport",
		"Stat:statistics - statystyka",
		"superl:superlative - stopieñ najwy¿szy",
		"Tax:tax - podatki",			/// XXX
		"Tech:technology - technika",
		"Telcom:telecommunications - telekomunikacja",
		"Telecom:telecommunications - telekomunikacja",
		"Tex:textiles - w³ókiennictwo",
		"Theat:theatre - teatr",
		"Tourism:tourism - turystyka",		/// XXX
		"Transp:tranport - transport",
		"Turf:turf - wy¶cigi konne",
		"TV:television - telewizja",
		"Univ:university - szkolnictwo wy¿sze",
		"US:American English - angielszczyzna amerykañska",
		"v:verb - czasownik",
		"v aux:auxiliary verb - czasownik posi³kowy",
		"v impers:impersonal verb - czasownik nieosobowy",
		"Vet:veterinary medicine - weterynaria",
		"vi:intransitive verb - czasownik nieprzechodni",
		"vinfml:very informal - pospolite",
		"vr:reflexive verb - czasownik zwrotny",
		"vt:transitive verb - czasownik przechodni",
		"vulg:vulgar or taboo - wulgarne",
		"Wine:winemaking - winiarstwo",
		"Zool:zoology - zoologia",
		"3rd pers:third person - forma trzeciej osoby", // XXX
		"3rd person:third person - forma trzeciej osoby", // XXX
		"XXXYYYZZZ" };
