
/*
    these are tooltips in format:
    "<original abbreviation>:<description-english> - <description-polish>"
    one per line - alphabetical order
    "XXXYYYZZZ" must be the last one
    
    marked with XXX - probably present in the dictionary, but not on its cheatsheet
 */

    static QString tab[] = {
		"abbr:abbreviation - skrót",
		"acc:accusative - biernik",
		"adj:adjective - przymiotnik",
		"adv:adverb - przys³ówek",
		"art:article - rodzajnik",
		"attr:attribute - przydawka",
		"aux:auxiliary - pomocniczy",
		"cmp:compound - wyraz z³o¿ony",
		"conj:conjunction - spójnik",
		"cpd:compound - wyraz z³o¿ony",
		"dat:dative - celownik",
		"decl:declined - odmienny",
		"dimin:diminutive - zdrobnienie",
		"etc:et cetera - itd.",
		"excl:exclamation - wykrzyknik",
		"f:feminine - ¿eñski",
		"fig:figurative - przeno¶ny",
		"fml:formal - formalny",
		"fus:inseparable verb - czasownik nierozdzielny",
		"gen:genitive - dope³niacz",
		"imp:imperative - tryb rozkazuj±cy",
		"im)perf:imperfect tense - czas przesz³y o aspekcie niedokonanym",
		"inf:informal - potocznie",
		"inf!:offensiv - obra¼liwy, wulgarny",
		"indef:indefinite - nieokre¶lony",
		"infin:infinitive - bezokolicznik",
		"instr:instrumental - narzêdnik",
		"inv:invariable - niezmienny",
		"irreg:irregular - nieregularny",
		"lit:literal - dos³owny",
		"loc:locative - miejscownik",
		"m:masculine - mêski",
		"m(f:masculine(feminine) - mêski(¿eñski)",
		"n:noun - rzeczownik",
		"nom:nominative - mianownik",
		"n(pl:??? - ???",
		"npl:plural noun - rzeczownik w liczbie mnogiej",
		"nt:neuter - nijaki",
		"num:number - liczba",
		"nvir:nonvirile - niemêskoosobowy",
		"part:particle - partyku³a",
		"pej:pejorative - pejoratywny",
		"perf:perfective verb - czasownik dokonany",
		"post:postpositiv (does not immediately precede a noun) - nie wystêpuje bezpo¶rednio przed rzeczownikiem",
		"pot:informal - potocznie",
		"pot!:obra¼liwy - offensiv",
		"pref:prefix - przedrostek",
		"prep:preposition - przyimek",
		"pron:pronoun - zaimek",
		"pl:plural - liczba mnoga",
		"pp:past participle - imies³ów czasu przesz³ego",
		"pt:past tense - czas przesz³y",
		"sg:singular - liczba pojedyncza",
		"suff:suffix - przyrostek",
		"vb:verb - czasownik",
		"vi:intransitive verb - czasownik nieprzechodni",
		"vir:virile - mêskoosobowy",
		"vr:reflexiv verb - czasownik zwrotny",
		"vt:transitive verb - czasownik przechodni",
		"ADMIN:administration - administracja",
		"AGR:agriculture - rolnictwo",
		"ANAT:anatomy - anatomia",
		"ARCHIT:architecture - architektura",
		"ASTRON:astronomy - astronomia",
		"AUT:automobiles - motoryzacja",
		"AVIAT:lotnictwo - aviation",
		"BIO:biology - biologia",
		"BOT:botany - botanika",
		"BRIT:British English - angielszczyzna brytyjska",
		"BUD:budownictwo - construction",
		"CHEM:chemistry - chemia",
		"COMM:commerce - handel",
		"COMPUT:computer - informatyka i komputery",
		"CONSTR:construction - budownictwo",
		"CULIN:culinary - kulinarny",
		"DRUK:poligrafia - printing",
		"ECON:economy - ekonomia",
		"EKON:ekonomia - economy",
		"ELEC:electronics, eletricity - elektronika, elektryczno¶æ",
		"ELEKTR:elektronika, elektryczno¶æ - electronics, eletricity",
		"FOT:fotografia - photography",
		"FIN:finance - finanse",
		"FIZ:fizyka - physics",
		"GEOG:geography - geografia",
		"GEOL:geology - geologia",
		"GEOM:geometria - geometry",
		"HIST:history - historia",
		"JÊZ:jêzykoznawstwo - linguistic",
		"JUR:law - prawo",
		"KOMPUT:komputery - computers",
		"KULIN:kulinarny - culinary",
		"LING:linguistic - jêzykoznawstwo",
		"LIT:literatura - literature",
		"LOT:lotnictwo - aviation",
		"MAT:matematyka - mathematics",
		"MATH:mathematics - matematyka",
		"MED:medicine - medycyna",
		"METEO:meteorology - meteorologia",
		"MIL:military - wojskowo¶æ",
		"MOT:motoryzacja - automobiles",
		"MUS:music - muzyka",
		"MUZ:muzyka - music",
		"NAUT:nautical - ¿egluga",
		"PHOT:photography - fotografia",
		"PHYSIOL:physiology - fizjologia",
		"POL:politics - polityka",
		"PSYCH:psychology - psychologia",
		"RAIL:railways - kolej",
		"REL:religion - religia",
		"ROL:rolnictwo - agriculture",
		"SCOL:school - szko³a",
		"SPORT:sport - sportowy",
		"SZKOL:szko³a - school",
		"TECH:technology - technika i technologia",
		"TEL:telecommunication - telekomunikacja",
		"THEAT:theatre - teatr",
		"TYP:printing - poligrafia",
		"UNIV:university - uniwersytet",
		"US:American English - angielszczyzna amerykañska",
		"WOJSK:wojskowo¶æ - military",
		"ZOOL:zoology - zoologia",
		"¯EGL:¿egluga - nautical",
		"XXXYYYZZZ" };
